#!/usr/bin/env bash

if [ "$1" != "" ]; then
   GUN=$1
else
   echo "Need GUN"
   exit
fi

cert_name=`echo $GUN | sed 's/\//_/g'`

# set to true for debugging openssl logging
if false; then 
  REDIRECT=/dev/tty
else 
  REDIRECT=/dev/null
fi

cat > "$cert_name.cnf" <<EOL
[repo_ext]
authorityKeyIdentifier=keyid,issuer
basicConstraints = critical,CA:FALSE
extendedKeyUsage=serverAuth,clientAuth
keyUsage = critical, digitalSignature, keyEncipherment
subjectAltName = DNS:notary-signer, DNS:notarysigner, DNS:localhost, IP:127.0.0.1
subjectKeyIdentifier=hash
EOL

commonname="CN=$GUN"

#NOTE:  Leaving out O= orgname for now
subj="/${commonname//\//\\/}"

openssl req -new -key "certificates_repo/notary_root.key" \
	-out "$cert_name.csr" \
	-sha256 \
	-passin pass:"weakpass" \
        -subj "$subj"

openssl x509 -req -days 750 -in "$cert_name.csr" -sha256 \
        -CA "certificates_ca/intermediate-ca.crt" \
	-CAkey "certificates_ca/intermediate-ca.key"  \
	-CAcreateserial \
        -out "$cert_name.crt" \
	-extfile "$cert_name.cnf" \
	-extensions repo_ext

rm "$cert_name.cnf" "$cert_name.csr"

# append the intermediate cert to this one to make it a proper bundle
cat "certificates_ca/intermediate-ca.crt" >> "$cert_name.crt"

openssl verify -CAfile certificates_ca/cacerts.crt $cert_name.crt

mkdir -p certificates_repo
mv $cert_name.crt certificates_repo/

