#! /bin/bash

set -x

if [ "$1" != "" ]; then
   id=$1
else
   id="docker.com/$RANDOM"
fi

gen_repo $id

echo Generating $id repo

cert_name=`echo $id | sed 's/\//_/g'`

notary init --rootcert certificates_repo/$cert_name.crt --rootkey certificates_repo/notary_root.key $id

notary add $id v1 ~/bin/setup.sh

#~/data/getcert.sh docker.com/notary/$id

notary publish $id

rm -rf ~/.notary/tuf/$id

#test the trust_pinning
notary list $id
